/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/vtlrm5ctWgUmzQnw/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#815699']} />
      <fog attach="fog" args={['#815699', 666.667, 482.052]} />
      <group {...props} dispose={null}>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={3.06}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1058.4645}
          shadow-camera-right={1058.4645}
          shadow-camera-top={1058.4645}
          shadow-camera-bottom={-1058.4645}
          position={[2338.05, 736.79, 300]}
        />
        <group name="AboutME" position={[-228.64, 19.1, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group name="About Me" position={[-144.07, 154.06, 3.77]} rotation={[0, 0, 0]} scale={0.1}>
            <group name="Group 2" position={[2646.36, -1877.93, 194.51]}>
              <mesh
                name="Text"
                geometry={nodes.Text.geometry}
                material={materials['Text Material']}
                castShadow
                receiveShadow
                position={[-312.79, -118.58, -40]}
                rotation={[0, 0, 0.36]}
                scale={[11.71, 10, 10]}
              />
            </group>
            <group name="Group" position={[1500.2, -1500.1, 71.16]}>
              <mesh
                name="Shape 0"
                geometry={nodes['Shape 0'].geometry}
                material={materials['Shape 0 Material']}
                castShadow
                receiveShadow
                position={[-1112.5, 1112.5, -64]}
              />
            </group>
            <mesh
              name="Rectangle 4"
              geometry={nodes['Rectangle 4'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[1440.69, -1540.64, -310]}
              rotation={[0, 0, 0]}
              scale={10}
            />
          </group>
        </group>
        <group name="MAIL" position={[116.71, -324.44, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh
            name="Extrude"
            geometry={nodes.Extrude.geometry}
            material={nodes.Extrude.material}
            castShadow
            position={[-45.96, 44.84, 60.81]}
            scale={1}
          />
          <mesh
            name="Rectangle 5"
            geometry={nodes['Rectangle 5'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[0, 0, -27.6]}
            scale={1}
          />
        </group>
        <group name="2070" position={[-574, -324.44, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.1}>
          <group
            name="2070 [Converted] copy caps"
            position={[-1507.07, 1636.86, 7.97]}
            rotation={[0, 0, 0]}
            scale={[1.02, 1.03, 8.04]}
          >
            <mesh
              name="Shape 01"
              geometry={nodes['Shape 01'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[590.79, -725.36, 0]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 1"
              geometry={nodes['Shape 1'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[1688.59, -1048.07, -1.84]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 2"
              geometry={nodes['Shape 2'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[1512.39, -725.45, -1.54]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 3"
              geometry={nodes['Shape 3'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[590.88, -1728.43, 0.02]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 4"
              geometry={nodes['Shape 4'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[1688.58, -2051.05, -1.82]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 5"
              geometry={nodes['Shape 5'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[1512.39, -1728.43, -1.52]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 6"
              geometry={nodes['Shape 6'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[647.79, -1525.61, -0.05]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 7"
              geometry={nodes['Shape 7'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[1398.07, -1525.61, -1.31]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
            <mesh
              name="Shape 8"
              geometry={nodes['Shape 8'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[2198.6, -1525.61, -2.65]}
              rotation={[0, -0.07, 0]}
              scale={[0.99, 0.98, 0.74]}
            />
          </group>
          <group name="Group 21" position={[7.72, -29.16, 10.89]}>
            <mesh
              name="Shape 02"
              geometry={nodes['Shape 02'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[-876.81, 900.1, 19.21]}
            />
            <mesh
              name="Shape 11"
              geometry={nodes['Shape 11'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[63.11, 900.1, 25.06]}
            />
            <mesh
              name="Shape 21"
              geometry={nodes['Shape 21'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[-881.63, -128, 21]}
            />
            <mesh
              name="Shape 31"
              geometry={nodes['Shape 31'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[66.1, -134.1, 29.36]}
            />
            <mesh
              name="Shape 41"
              geometry={nodes['Shape 41'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[-823.22, 68, -34.36]}
            />
            <mesh
              name="Shape 51"
              geometry={nodes['Shape 51'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[-53.8, 68, -34.35]}
            />
            <mesh
              name="Shape 61"
              geometry={nodes['Shape 61'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[766.33, 68, -34.34]}
            />
          </group>
          <mesh
            name="Rectangle 51"
            geometry={nodes['Rectangle 51'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[0, 0, -333.83]}
            scale={10.52}
          />
        </group>
        <group name="ESHOP" position={[116.71, 359, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group name="eshop" position={[-100.13, 108.76, 10.38]} scale={0.3}>
            <mesh
              name="Shape 22"
              geometry={nodes['Shape 22'].geometry}
              material={materials['Shape 22 Material']}
              castShadow
              receiveShadow
              position={[34.48, -20.23, -7.26]}
            />
            <mesh
              name="Rectangle 3"
              geometry={nodes['Rectangle 3'].geometry}
              material={materials['Untitled Material']}
              castShadow
              receiveShadow
              position={[333.76, -362.54, -109.97]}
              scale={3.33}
            />
          </group>
        </group>
        <group name="Arts Palette" position={[-574, 359, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={1}>
          <group
            name="PaletteSTROKE"
            position={[-111.12, 118.23, 9.64]}
            rotation={[-0.02, 0, 0]}
            scale={[0.05, 0.06, 0.08]}
          >
            <mesh
              name="Sphere 4"
              geometry={nodes['Sphere 4'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[338.44, -3680.12, 60.23]}
              rotation={[0, 0, 0]}
              scale={[14.74, 14.74, 11.38]}
            />
            <mesh
              name="Sphere 3"
              geometry={nodes['Sphere 3'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[3740.93, -3680.12, 60.23]}
              rotation={[0, 0, 0]}
              scale={[14.74, 14.74, 11.38]}
            />
            <mesh
              name="Sphere 2"
              geometry={nodes['Sphere 2'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[3740.93, -308.87, 60.23]}
              rotation={[0, 0, 0]}
              scale={[14.74, 14.74, 11.38]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[338.44, -308.87, 60.23]}
              rotation={[0, 0, 0]}
              scale={[14.74, 14.74, 11.38]}
            />
            <mesh
              name="Shape 03"
              geometry={nodes['Shape 03'].geometry}
              material={materials[' ']}
              castShadow
              receiveShadow
              position={[264.5, -217.5, 0]}
            />
          </group>
          <mesh
            name="SVG_PaletteArts"
            geometry={nodes.SVG_PaletteArts.geometry}
            material={materials['Gradient ']}
            castShadow
            receiveShadow
            position={[-85.92, 69.69, 16.1]}
            scale={0.08}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[0, 0, -22.71]}
          />
        </group>
        <group name="Rectangle1" position={[-228.64, 17.28, 0]}>
          <mesh
            name="Rectangle 52"
            geometry={nodes['Rectangle 52'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[0, -341.72, 0]}
          />
          <mesh
            name="Rectangle 41"
            geometry={nodes['Rectangle 41'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[345.36, 1.82, 0]}
          />
          <mesh
            name="Rectangle 42"
            geometry={nodes['Rectangle 42'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[-345.36, 1.82, 0]}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['Untitled Material']}
            castShadow
            receiveShadow
            position={[0, 341.72, 0]}
          />
        </group>
        <PerspectiveCamera
          name="Face 2"
          makeDefault={true}
          far={100000}
          near={5}
          fov={45}
          position={[-662.34, -5.5, 1976.45]}
          rotation={[0, 0, 0]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.77} color="#eaeaea" />
      </group>
    </>
  )
}
